/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Regolith {
  constructor()
  doMatch(text: string, pattern: string): boolean
  compile(pattern: string): boolean
  test(text: string): boolean
}
