/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Regolith {
  constructor(pattern: string, flags?: string | undefined | null)
  test(input: string): boolean
  exec(input: string): Array<string> | null
  match(input: string): Array<string> | null
  replace(input: string, replacement: string): string
  search(input: string): number
  split(input: string, limit?: number | undefined | null): Array<string>
  get source(): string
  get flags(): string
  get global(): boolean
  get ignoreCase(): boolean
  get multiline(): boolean
}
